// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geodesity.proto

/*
Package geodesity is a generated protocol buffer package.

It is generated from these files:
	geodesity.proto

It has these top-level messages:
	Event
	Heartbeat
	Position
	IdleNotify
	ParkNotify
*/
package geodesity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enums
//
type EventType int32

const (
	EventType_EVENT_INVALID        EventType = 0
	EventType_EVENT_HEARTBEAT      EventType = 1
	EventType_EVENT_POSITION_TIMED EventType = 2
	EventType_EVENT_IDLE_NOTIFY    EventType = 3
	EventType_EVENT_PARK_NOTIFY    EventType = 4
)

var EventType_name = map[int32]string{
	0: "EVENT_INVALID",
	1: "EVENT_HEARTBEAT",
	2: "EVENT_POSITION_TIMED",
	3: "EVENT_IDLE_NOTIFY",
	4: "EVENT_PARK_NOTIFY",
}
var EventType_value = map[string]int32{
	"EVENT_INVALID":        0,
	"EVENT_HEARTBEAT":      1,
	"EVENT_POSITION_TIMED": 2,
	"EVENT_IDLE_NOTIFY":    3,
	"EVENT_PARK_NOTIFY":    4,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotifyType int32

const (
	NotifyType_NOTIFY_INVALID       NotifyType = 0
	NotifyType_NOTIFY_ENTER_IDLE    NotifyType = 1
	NotifyType_NOTIFY_CONTINUE_IDLE NotifyType = 2
	NotifyType_NOTIFY_LEAVE_IDLE    NotifyType = 3
)

var NotifyType_name = map[int32]string{
	0: "NOTIFY_INVALID",
	1: "NOTIFY_ENTER_IDLE",
	2: "NOTIFY_CONTINUE_IDLE",
	3: "NOTIFY_LEAVE_IDLE",
}
var NotifyType_value = map[string]int32{
	"NOTIFY_INVALID":       0,
	"NOTIFY_ENTER_IDLE":    1,
	"NOTIFY_CONTINUE_IDLE": 2,
	"NOTIFY_LEAVE_IDLE":    3,
}

func (x NotifyType) String() string {
	return proto.EnumName(NotifyType_name, int32(x))
}
func (NotifyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Main Event - All protocols derive from this message.
//
type Event struct {
	Id        string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type      EventType                  `protobuf:"varint,2,opt,name=type,enum=EventType" json:"type,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*Event_Heartbeat
	//	*Event_Position
	//	*Event_IdleNotify
	//	*Event_ParkNotify
	Details isEvent_Details `protobuf_oneof:"Details"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isEvent_Details interface {
	isEvent_Details()
}

type Event_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,100,opt,name=heartbeat,oneof"`
}
type Event_Position struct {
	Position *Position `protobuf:"bytes,101,opt,name=position,oneof"`
}
type Event_IdleNotify struct {
	IdleNotify *IdleNotify `protobuf:"bytes,102,opt,name=idle_notify,json=idleNotify,oneof"`
}
type Event_ParkNotify struct {
	ParkNotify *ParkNotify `protobuf:"bytes,103,opt,name=park_notify,json=parkNotify,oneof"`
}

func (*Event_Heartbeat) isEvent_Details()  {}
func (*Event_Position) isEvent_Details()   {}
func (*Event_IdleNotify) isEvent_Details() {}
func (*Event_ParkNotify) isEvent_Details() {}

func (m *Event) GetDetails() isEvent_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EVENT_INVALID
}

func (m *Event) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetDetails().(*Event_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *Event) GetPosition() *Position {
	if x, ok := m.GetDetails().(*Event_Position); ok {
		return x.Position
	}
	return nil
}

func (m *Event) GetIdleNotify() *IdleNotify {
	if x, ok := m.GetDetails().(*Event_IdleNotify); ok {
		return x.IdleNotify
	}
	return nil
}

func (m *Event) GetParkNotify() *ParkNotify {
	if x, ok := m.GetDetails().(*Event_ParkNotify); ok {
		return x.ParkNotify
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_Heartbeat)(nil),
		(*Event_Position)(nil),
		(*Event_IdleNotify)(nil),
		(*Event_ParkNotify)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// Details
	switch x := m.Details.(type) {
	case *Event_Heartbeat:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Heartbeat); err != nil {
			return err
		}
	case *Event_Position:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Position); err != nil {
			return err
		}
	case *Event_IdleNotify:
		b.EncodeVarint(102<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IdleNotify); err != nil {
			return err
		}
	case *Event_ParkNotify:
		b.EncodeVarint(103<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ParkNotify); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Details has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 100: // Details.heartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Heartbeat)
		err := b.DecodeMessage(msg)
		m.Details = &Event_Heartbeat{msg}
		return true, err
	case 101: // Details.position
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Position)
		err := b.DecodeMessage(msg)
		m.Details = &Event_Position{msg}
		return true, err
	case 102: // Details.idle_notify
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IdleNotify)
		err := b.DecodeMessage(msg)
		m.Details = &Event_IdleNotify{msg}
		return true, err
	case 103: // Details.park_notify
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ParkNotify)
		err := b.DecodeMessage(msg)
		m.Details = &Event_ParkNotify{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// Details
	switch x := m.Details.(type) {
	case *Event_Heartbeat:
		s := proto.Size(x.Heartbeat)
		n += proto.SizeVarint(100<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Position:
		s := proto.Size(x.Position)
		n += proto.SizeVarint(101<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_IdleNotify:
		s := proto.Size(x.IdleNotify)
		n += proto.SizeVarint(102<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_ParkNotify:
		s := proto.Size(x.ParkNotify)
		n += proto.SizeVarint(103<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Heartbeat - Device wakeup/keep-alive message
//
type Heartbeat struct {
	Sequence uint32 `protobuf:"varint,300,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Heartbeat) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// Position - General location message
//
type Position struct {
	Longitude float32 `protobuf:"fixed32,301,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float32 `protobuf:"fixed32,302,opt,name=latitude" json:"latitude,omitempty"`
	Altitude  float32 `protobuf:"fixed32,303,opt,name=altitude" json:"altitude,omitempty"`
	Course    float32 `protobuf:"fixed32,304,opt,name=course" json:"course,omitempty"`
	Speed     float32 `protobuf:"fixed32,305,opt,name=speed" json:"speed,omitempty"`
	Odometer  float32 `protobuf:"fixed32,306,opt,name=odometer" json:"odometer,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Position) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Position) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Position) GetAltitude() float32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Position) GetCourse() float32 {
	if m != nil {
		return m.Course
	}
	return 0
}

func (m *Position) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Position) GetOdometer() float32 {
	if m != nil {
		return m.Odometer
	}
	return 0
}

// IdleNotify - Reported when a device recognizes idle start, continue, or end
//
type IdleNotify struct {
	PositionTimed *Position  `protobuf:"bytes,307,opt,name=position_timed,json=positionTimed" json:"position_timed,omitempty"`
	Type          NotifyType `protobuf:"varint,308,opt,name=type,enum=NotifyType" json:"type,omitempty"`
	Seconds       uint32     `protobuf:"varint,309,opt,name=seconds" json:"seconds,omitempty"`
}

func (m *IdleNotify) Reset()                    { *m = IdleNotify{} }
func (m *IdleNotify) String() string            { return proto.CompactTextString(m) }
func (*IdleNotify) ProtoMessage()               {}
func (*IdleNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IdleNotify) GetPositionTimed() *Position {
	if m != nil {
		return m.PositionTimed
	}
	return nil
}

func (m *IdleNotify) GetType() NotifyType {
	if m != nil {
		return m.Type
	}
	return NotifyType_NOTIFY_INVALID
}

func (m *IdleNotify) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

// ParkNotify - Reported when a device recognizes park start, continue, or end
//
type ParkNotify struct {
	PositionTimed *Position  `protobuf:"bytes,310,opt,name=position_timed,json=positionTimed" json:"position_timed,omitempty"`
	Type          NotifyType `protobuf:"varint,311,opt,name=type,enum=NotifyType" json:"type,omitempty"`
	Seconds       uint32     `protobuf:"varint,312,opt,name=seconds" json:"seconds,omitempty"`
}

func (m *ParkNotify) Reset()                    { *m = ParkNotify{} }
func (m *ParkNotify) String() string            { return proto.CompactTextString(m) }
func (*ParkNotify) ProtoMessage()               {}
func (*ParkNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ParkNotify) GetPositionTimed() *Position {
	if m != nil {
		return m.PositionTimed
	}
	return nil
}

func (m *ParkNotify) GetType() NotifyType {
	if m != nil {
		return m.Type
	}
	return NotifyType_NOTIFY_INVALID
}

func (m *ParkNotify) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*Heartbeat)(nil), "Heartbeat")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*IdleNotify)(nil), "IdleNotify")
	proto.RegisterType((*ParkNotify)(nil), "ParkNotify")
	proto.RegisterEnum("EventType", EventType_name, EventType_value)
	proto.RegisterEnum("NotifyType", NotifyType_name, NotifyType_value)
}

func init() { proto.RegisterFile("geodesity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcb, 0x6f, 0xd3, 0x40,
	0x10, 0xc6, 0x13, 0xf7, 0xe9, 0x89, 0x9a, 0xa6, 0x0b, 0x15, 0x4b, 0x11, 0x10, 0xe5, 0x42, 0xd4,
	0xc3, 0x56, 0x94, 0x4b, 0xaf, 0x09, 0x31, 0xc4, 0xa2, 0x38, 0xd1, 0x62, 0x2a, 0x71, 0x8a, 0xdc,
	0xee, 0x36, 0x5d, 0xd5, 0xf5, 0x1a, 0x7b, 0x83, 0x14, 0xc1, 0x5f, 0x84, 0x78, 0xb4, 0xbc, 0xff,
	0x3c, 0x64, 0xaf, 0xd7, 0x0e, 0x15, 0x87, 0x1e, 0xe7, 0xf7, 0x7d, 0x9e, 0x6f, 0x35, 0x33, 0x32,
	0x6c, 0x4e, 0xb9, 0x64, 0x3c, 0x15, 0x6a, 0x4e, 0xe2, 0x44, 0x2a, 0xb9, 0xf3, 0x70, 0x2a, 0xe5,
	0x34, 0xe4, 0x7b, 0x79, 0x75, 0x3c, 0x3b, 0xdd, 0x53, 0xe2, 0x82, 0xa7, 0x2a, 0xb8, 0x88, 0xb5,
	0xa1, 0x73, 0x65, 0xc1, 0x8a, 0xf3, 0x8e, 0x47, 0x0a, 0x35, 0xc1, 0x12, 0x0c, 0xd7, 0xdb, 0xf5,
	0xae, 0x4d, 0x2d, 0xc1, 0xd0, 0x03, 0x58, 0x56, 0xf3, 0x98, 0x63, 0xab, 0x5d, 0xef, 0x36, 0xf7,
	0x81, 0xe4, 0x2e, 0x7f, 0x1e, 0x73, 0x9a, 0x73, 0x74, 0x00, 0x76, 0xd9, 0x0c, 0x2f, 0xb5, 0xeb,
	0xdd, 0xc6, 0xfe, 0x0e, 0xd1, 0x71, 0xc4, 0xc4, 0x11, 0xdf, 0x38, 0x68, 0x65, 0x46, 0xbb, 0x60,
	0x9f, 0xf1, 0x20, 0x51, 0xc7, 0x3c, 0x50, 0x98, 0xe5, 0x5f, 0x02, 0x19, 0x1a, 0x32, 0xac, 0xd1,
	0x4a, 0x46, 0x8f, 0x60, 0x3d, 0x96, 0xa9, 0x50, 0x42, 0x46, 0x98, 0xe7, 0x56, 0x9b, 0x8c, 0x0b,
	0x30, 0xac, 0xd1, 0x52, 0x44, 0x04, 0x1a, 0x82, 0x85, 0x7c, 0x12, 0x49, 0x25, 0x4e, 0xe7, 0xf8,
	0x34, 0xf7, 0x36, 0x88, 0xcb, 0x42, 0xee, 0xe5, 0x68, 0x58, 0xa3, 0x20, 0xca, 0x2a, 0xf3, 0xc7,
	0x41, 0x72, 0x6e, 0xfc, 0xd3, 0xc2, 0x3f, 0x0e, 0x92, 0xf3, 0xca, 0x1f, 0x97, 0x55, 0xdf, 0x86,
	0xb5, 0x01, 0x57, 0x81, 0x08, 0xd3, 0x4e, 0x17, 0xec, 0xf2, 0xb5, 0xe8, 0x1e, 0xac, 0xa7, 0xfc,
	0xed, 0x8c, 0x47, 0x27, 0x1c, 0x7f, 0xca, 0x66, 0xb5, 0x41, 0x4b, 0xd0, 0xb9, 0xac, 0xc3, 0xba,
	0x79, 0x2d, 0xba, 0x0f, 0x76, 0x28, 0xa3, 0xa9, 0x50, 0x33, 0xc6, 0xf1, 0xe7, 0xcc, 0x6a, 0xd1,
	0x8a, 0x64, 0x8d, 0xc2, 0x40, 0x69, 0xf5, 0x8b, 0x56, 0x4b, 0x90, 0x89, 0x41, 0x58, 0x88, 0x5f,
	0x0b, 0xd1, 0x00, 0x74, 0x07, 0x56, 0x4f, 0xe4, 0x2c, 0x49, 0x39, 0xbe, 0xd4, 0x52, 0x51, 0xa2,
	0x6d, 0x58, 0x49, 0x63, 0xce, 0x19, 0xbe, 0xd2, 0x5c, 0x57, 0x59, 0x33, 0xc9, 0xe4, 0x05, 0x57,
	0x3c, 0xc1, 0xdf, 0x8a, 0x66, 0x06, 0x74, 0x3e, 0x00, 0x54, 0x33, 0x43, 0x8f, 0xa1, 0x69, 0x26,
	0x3c, 0xc9, 0x16, 0xc8, 0xf0, 0x77, 0xeb, 0xda, 0x16, 0xe8, 0x86, 0x71, 0x64, 0xcb, 0x66, 0xa8,
	0x5d, 0xdc, 0xcd, 0x0f, 0x7d, 0x38, 0x0d, 0xa2, 0x5b, 0x2d, 0x5c, 0xce, 0x5d, 0x58, 0x4b, 0xf9,
	0x89, 0x8c, 0x58, 0x8a, 0x7f, 0xea, 0x89, 0x99, 0x3a, 0x4b, 0xaf, 0x36, 0xf0, 0x9f, 0xf4, 0x5f,
	0x37, 0x4d, 0xff, 0x7d, 0x93, 0xf4, 0x3f, 0xff, 0xa6, 0xef, 0xbe, 0x07, 0xbb, 0xbc, 0x72, 0xb4,
	0x05, 0x1b, 0xce, 0x91, 0xe3, 0xf9, 0x13, 0xd7, 0x3b, 0xea, 0x1d, 0xba, 0x83, 0x56, 0x0d, 0xdd,
	0x82, 0x4d, 0x8d, 0x86, 0x4e, 0x8f, 0xfa, 0x7d, 0xa7, 0xe7, 0xb7, 0xea, 0x08, 0xc3, 0x6d, 0x0d,
	0xc7, 0xa3, 0x57, 0xae, 0xef, 0x8e, 0xbc, 0x89, 0xef, 0xbe, 0x74, 0x06, 0x2d, 0x0b, 0x6d, 0xc3,
	0x56, 0xd1, 0x61, 0x70, 0xe8, 0x4c, 0xbc, 0x91, 0xef, 0x3e, 0x7b, 0xd3, 0x5a, 0xaa, 0xf0, 0xb8,
	0x47, 0x5f, 0x18, 0xbc, 0xbc, 0x7b, 0x06, 0x50, 0xbd, 0x15, 0x21, 0x68, 0x6a, 0x65, 0x21, 0x7e,
	0x1b, 0xb6, 0x0a, 0xe6, 0x78, 0xbe, 0x43, 0xf3, 0xb6, 0xfa, 0x01, 0x05, 0x7e, 0x3a, 0xf2, 0x7c,
	0xd7, 0x7b, 0xed, 0x68, 0xc5, 0x5a, 0xf8, 0xe0, 0xd0, 0xe9, 0x1d, 0x15, 0x78, 0xa9, 0x7f, 0x00,
	0x48, 0x48, 0x72, 0xed, 0x57, 0xd1, 0xdf, 0x7c, 0x6e, 0xc0, 0x38, 0xab, 0xd3, 0x8f, 0x56, 0xab,
	0x24, 0x44, 0xa3, 0xe3, 0xd5, 0xdc, 0xfa, 0xe4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x0b,
	0xfb, 0x46, 0x68, 0x04, 0x00, 0x00,
}
