# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geodesity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geodesity.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fgeodesity.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.EventType\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1f\n\theartbeat\x18\x64 \x01(\x0b\x32\n.HeartbeatH\x00\x12\x1d\n\x08position\x18\x65 \x01(\x0b\x32\t.PositionH\x00\x12\"\n\x0bidle_notify\x18\x66 \x01(\x0b\x32\x0b.IdleNotifyH\x00\x12\"\n\x0bpark_notify\x18g \x01(\x0b\x32\x0b.ParkNotifyH\x00\x42\t\n\x07\x44\x65tails\"\x1e\n\tHeartbeat\x12\x11\n\x08sequence\x18\xac\x02 \x01(\r\"x\n\x08Position\x12\x12\n\tlongitude\x18\xad\x02 \x01(\x02\x12\x11\n\x08latitude\x18\xae\x02 \x01(\x02\x12\x11\n\x08\x61ltitude\x18\xaf\x02 \x01(\x02\x12\x0f\n\x06\x63ourse\x18\xb0\x02 \x01(\x02\x12\x0e\n\x05speed\x18\xb1\x02 \x01(\x02\x12\x11\n\x08odometer\x18\xb2\x02 \x01(\x02\"^\n\nIdleNotify\x12\"\n\x0eposition_timed\x18\xb3\x02 \x01(\x0b\x32\t.Position\x12\x1a\n\x04type\x18\xb4\x02 \x01(\x0e\x32\x0b.NotifyType\x12\x10\n\x07seconds\x18\xb5\x02 \x01(\r\"^\n\nParkNotify\x12\"\n\x0eposition_timed\x18\xb6\x02 \x01(\x0b\x32\t.Position\x12\x1a\n\x04type\x18\xb7\x02 \x01(\x0e\x32\x0b.NotifyType\x12\x10\n\x07seconds\x18\xb8\x02 \x01(\r*{\n\tEventType\x12\x11\n\rEVENT_INVALID\x10\x00\x12\x13\n\x0f\x45VENT_HEARTBEAT\x10\x01\x12\x18\n\x14\x45VENT_POSITION_TIMED\x10\x02\x12\x15\n\x11\x45VENT_IDLE_NOTIFY\x10\x03\x12\x15\n\x11\x45VENT_PARK_NOTIFY\x10\x04*h\n\nNotifyType\x12\x12\n\x0eNOTIFY_INVALID\x10\x00\x12\x15\n\x11NOTIFY_ENTER_IDLE\x10\x01\x12\x18\n\x14NOTIFY_CONTINUE_IDLE\x10\x02\x12\x15\n\x11NOTIFY_LEAVE_IDLE\x10\x03\x42\x38\n\x12io.geodesity.protoB\x0fGeodesityProtos\xaa\x02\x10Geodesity.Protosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVENT_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_HEARTBEAT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_POSITION_TIMED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_IDLE_NOTIFY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_PARK_NOTIFY', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=640,
  serialized_end=763,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
_NOTIFYTYPE = _descriptor.EnumDescriptor(
  name='NotifyType',
  full_name='NotifyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTIFY_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFY_ENTER_IDLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFY_CONTINUE_IDLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFY_LEAVE_IDLE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=765,
  serialized_end=869,
)
_sym_db.RegisterEnumDescriptor(_NOTIFYTYPE)

NotifyType = enum_type_wrapper.EnumTypeWrapper(_NOTIFYTYPE)
EVENT_INVALID = 0
EVENT_HEARTBEAT = 1
EVENT_POSITION_TIMED = 2
EVENT_IDLE_NOTIFY = 3
EVENT_PARK_NOTIFY = 4
NOTIFY_INVALID = 0
NOTIFY_ENTER_IDLE = 1
NOTIFY_CONTINUE_IDLE = 2
NOTIFY_LEAVE_IDLE = 3



_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Event.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Event.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Event.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat', full_name='Event.heartbeat', index=3,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='Event.position', index=4,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idle_notify', full_name='Event.idle_notify', index=5,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='park_notify', full_name='Event.park_notify', index=6,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Details', full_name='Event.Details',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=53,
  serialized_end=292,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='Heartbeat',
  full_name='Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='Heartbeat.sequence', index=0,
      number=300, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=324,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Position.longitude', index=0,
      number=301, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Position.latitude', index=1,
      number=302, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Position.altitude', index=2,
      number=303, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='course', full_name='Position.course', index=3,
      number=304, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='Position.speed', index=4,
      number=305, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='odometer', full_name='Position.odometer', index=5,
      number=306, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=446,
)


_IDLENOTIFY = _descriptor.Descriptor(
  name='IdleNotify',
  full_name='IdleNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position_timed', full_name='IdleNotify.position_timed', index=0,
      number=307, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='IdleNotify.type', index=1,
      number=308, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='IdleNotify.seconds', index=2,
      number=309, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=542,
)


_PARKNOTIFY = _descriptor.Descriptor(
  name='ParkNotify',
  full_name='ParkNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position_timed', full_name='ParkNotify.position_timed', index=0,
      number=310, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ParkNotify.type', index=1,
      number=311, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='ParkNotify.seconds', index=2,
      number=312, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=638,
)

_EVENT.fields_by_name['type'].enum_type = _EVENTTYPE
_EVENT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EVENT.fields_by_name['heartbeat'].message_type = _HEARTBEAT
_EVENT.fields_by_name['position'].message_type = _POSITION
_EVENT.fields_by_name['idle_notify'].message_type = _IDLENOTIFY
_EVENT.fields_by_name['park_notify'].message_type = _PARKNOTIFY
_EVENT.oneofs_by_name['Details'].fields.append(
  _EVENT.fields_by_name['heartbeat'])
_EVENT.fields_by_name['heartbeat'].containing_oneof = _EVENT.oneofs_by_name['Details']
_EVENT.oneofs_by_name['Details'].fields.append(
  _EVENT.fields_by_name['position'])
_EVENT.fields_by_name['position'].containing_oneof = _EVENT.oneofs_by_name['Details']
_EVENT.oneofs_by_name['Details'].fields.append(
  _EVENT.fields_by_name['idle_notify'])
_EVENT.fields_by_name['idle_notify'].containing_oneof = _EVENT.oneofs_by_name['Details']
_EVENT.oneofs_by_name['Details'].fields.append(
  _EVENT.fields_by_name['park_notify'])
_EVENT.fields_by_name['park_notify'].containing_oneof = _EVENT.oneofs_by_name['Details']
_IDLENOTIFY.fields_by_name['position_timed'].message_type = _POSITION
_IDLENOTIFY.fields_by_name['type'].enum_type = _NOTIFYTYPE
_PARKNOTIFY.fields_by_name['position_timed'].message_type = _POSITION
_PARKNOTIFY.fields_by_name['type'].enum_type = _NOTIFYTYPE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['IdleNotify'] = _IDLENOTIFY
DESCRIPTOR.message_types_by_name['ParkNotify'] = _PARKNOTIFY
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
DESCRIPTOR.enum_types_by_name['NotifyType'] = _NOTIFYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'geodesity_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  ))
_sym_db.RegisterMessage(Event)

Heartbeat = _reflection.GeneratedProtocolMessageType('Heartbeat', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEAT,
  __module__ = 'geodesity_pb2'
  # @@protoc_insertion_point(class_scope:Heartbeat)
  ))
_sym_db.RegisterMessage(Heartbeat)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'geodesity_pb2'
  # @@protoc_insertion_point(class_scope:Position)
  ))
_sym_db.RegisterMessage(Position)

IdleNotify = _reflection.GeneratedProtocolMessageType('IdleNotify', (_message.Message,), dict(
  DESCRIPTOR = _IDLENOTIFY,
  __module__ = 'geodesity_pb2'
  # @@protoc_insertion_point(class_scope:IdleNotify)
  ))
_sym_db.RegisterMessage(IdleNotify)

ParkNotify = _reflection.GeneratedProtocolMessageType('ParkNotify', (_message.Message,), dict(
  DESCRIPTOR = _PARKNOTIFY,
  __module__ = 'geodesity_pb2'
  # @@protoc_insertion_point(class_scope:ParkNotify)
  ))
_sym_db.RegisterMessage(ParkNotify)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022io.geodesity.protoB\017GeodesityProtos\252\002\020Geodesity.Protos'))
# @@protoc_insertion_point(module_scope)
